---
title: Pacific Food System Education Analysis
author: M.K. Lau
---

# Summary

Project files are on Google Drive:
https://drive.google.com/open?id=1imgIb_voKPfAizWXIeVZKX68lGW_sZw0&usp=drive_fs

## Things to do
- [X] Compare the different programs using Ebel
- [X] Compare the stated program description with the course descriptions using Ebel
- [X] Wordclouds
- [X] Princomp
- [X] Heatmap (notebook LM results)



```{r setup, echo = FALSE, results = "hide"}

if (!("pacman" %in% installed.packages()[, 1])) {
    
  install.packages("pacman")

} else {
    
  library(pacman)
  p_load(RCurl, XML, rvest, magrittr, wordcloud, 
         RColorBrewer, rmarkdown, bipartite, igraph, 
         googlesheets4, knitr, xtable, reshape2, gplots,
         corrr, ggcorrplot, FactoMineR, factoextra)

}

gs4_auth("mklau3@hawaii.edu")

```

```{r fse_deps, echo = TRUE}

#' Food System Education Analysis Functions
#'
#' This is a set of functions for analyzing food system
#' program data.
#'
#' @param x Text for a program.
#' @param kw Named list of key words.

analyze_kw <- function(x = "text", kw = "keywords"){

    x.collapse <- paste(x, collapse = " ")
    x.collapse <- tolower(x.collapse)

    out <- kw
    
    for (i in seq_along(kw)){
        for (j in seq_along(kw[[i]])){
            out[[i]][j] <- as.numeric(grepl(kw[[i]][j], x.collapse))
        }
    }
    
    out <- lapply(out, as.numeric)
    
    return(out)

}

#' Create alignment heat map
#'
#' @param x Alignment data frame.

quant_align <- function(x){
    x <- tolower(x)
    out <- c(grepl("weak", x), 
             grepl("partially", x),
             grepl("moderate", x),
             grepl("strongly", x),
             grepl("fully", x))
    out <- c(0, seq_along(out)[out])
    out <- max(out)
    return(out)
}

#' Return keyword list.
#'
#' @param x List of binary word presence vectors.
#' @param kw Keyword list. 

list_kw <- function(x = "word presences", kw = "keyword list"){
    out <- x 
    for (i in seq_along(x)){
        out[[i]] <- kw[[i]][x[[i]] == 1]
    }
    return(out)
}


```

```{r load_data}

## load data files
ebel <- readLines("data/ebel_framework_lo.txt")

scfs.courses <- readLines("data/scfs_courses.txt")
scfs.program <- readLines("data/scfs_program.txt")

ctahr.courses <- readLines("data/ctahr_courses.txt")
ctahr.program <- readLines("data/ctahr_program.txt")

usp.courses <- readLines("data/usp_courses.txt")
usp.program <- readLines("data/usp_program.txt")


tab.align <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1u3fUuchbD1iYc_YHG3pOZW60s0CRn2jdBpiKn89g-WY/", 
                                       sheet = "alignment_table")
tab.align <- as.data.frame(tab.align)
rownames(tab.align) <- tab.align[, 1]
tab.align <- tab.align[, -1]
hm.align <- apply(tab.align, 2, function(x) sapply(x, quant_align))

```


```{r ebel, echo = FALSE, results = "hide"}

ebel.head <- grep("\\#", ebel)
lo.kw <- ebel[(ebel.head[2] + 1):(ebel.head[3] - 1)]
lo.kw <- lo.kw[lo.kw != ""]
lo.kw <- lo.kw[!(grepl("Keywords:", lo.kw))]
kw.head <- grep("LO ", lo.kw)
kw <- list()
for (i in seq_along(kw.head)){
    if (i < length(kw.head)){
        kw [[i]] <- lo.kw[(kw.head[i] + 1):(kw.head[i + 1] - 1)]
    }else{
        kw [[i]] <- lo.kw[(kw.head[i] + 1):length(lo.kw)]
    }
}

kw[[4]] <- c(kw[[4]], "practical")
kw[[4]] <- c(kw[[4]], "training")
kw[[4]] <- c(kw[[4]], "experiential")
kw[[4]] <- c(kw[[4]], "project-based")
kw[[5]] <- c(kw[[5]], "written communication")
kw[[5]] <- c(kw[[5]], "oral communication")
kw[[5]] <- c(kw[[5]], "communication")
kw[[6]] <- c(kw[[6]], "leadership")

names(kw) <- lo.kw[kw.head]

for (i in seq_along(kw)){
    kw[[i]] <- unlist(strsplit(kw[[i]], " / "))
}

```


```{r analysis, echo = FALSE, results = "hide"}

kwa.scfs.courses <- analyze_kw(scfs.courses, kw)
kwa.scfs.program <- analyze_kw(scfs.program, kw)
kw.scfs.courses <- list_kw(kwa.scfs.courses, kw)
kw.scfs.program <- list_kw(kwa.scfs.program, kw)

kwa.ctahr.courses <- analyze_kw(ctahr.courses, kw)
kwa.ctahr.program <- analyze_kw(ctahr.program, kw)
kw.ctahr.courses <- list_kw(kwa.ctahr.courses, kw)
kw.ctahr.program <- list_kw(kwa.ctahr.program, kw)

kwa.usp.courses <- analyze_kw(usp.courses, kw)
kwa.usp.program <- analyze_kw(usp.program, kw)
kw.usp.courses <- list_kw(kwa.usp.courses, kw)
kw.usp.program <- list_kw(kwa.usp.program, kw)

kwa.all <- rbind(unlist(lapply(kwa.scfs.program, sum)),
                 unlist(lapply(kwa.scfs.courses, sum)),
                 unlist(lapply(kwa.ctahr.program, sum)),
                 unlist(lapply(kwa.ctahr.courses, sum)),
                 unlist(lapply(kwa.usp.program, sum)),
                 unlist(lapply(kwa.usp.courses, sum)))
rownames(kwa.all) <- c("scfs_program",
                       "scfs_courses",
                       "ctahr_program",
                       "ctahr_courses",
                       "usp_program",
                       "usp_courses")
kwa.d <- dist(kwa.all)
kwa.pc <- princomp(kwa.d)

kwa.kw.l <- list(kwa.scfs.program,
                 kwa.scfs.courses,
                 kwa.ctahr.program,
                 kwa.ctahr.courses,
                 kwa.usp.program,
                 kwa.usp.courses)

kwa.kw.d <- as.matrix(kwa.d)

for (i in seq(1, nrow(kwa.kw.d))){
    for (j in seq(1, ncol(kwa.kw.d))){
        kwa.kw.d[i, j] <- sum((unlist(kwa.kw.l[[i]]) - unlist(kwa.kw.l[[j]]))^2)
    }
}

kwa.kw.d <- as.dist(kwa.kw.d)
kwa.kw.pc <- princomp(kwa.kw.d)


wc.scfs.courses <- unlist(lapply(kwa.scfs.courses, sum))
wc.scfs.program <- unlist(lapply(kwa.scfs.program, sum))

wc.ctahr.courses <- unlist(lapply(kwa.ctahr.courses, sum))
wc.ctahr.program <- unlist(lapply(kwa.ctahr.program, sum))

wc.usp.courses <- unlist(lapply(kwa.usp.courses, sum))
wc.usp.program <- unlist(lapply(kwa.usp.program, sum))

align.hm <- apply(tab.align, 2, function(x) sapply(x, quant_align))

```

```{r result_heatmap, cache=TRUE, fig.dim = c(7, 8)}

hm2.in <- abs(max(hm.align) - hm.align)
## hm2.in <- hm.align
rownames(hm2.in) <- substr(rownames(hm.align), 1, 3)
colnames(hm2.in) <- c("USP", "CTAHR", "SCFS")[c(grep("USP", colnames(hm.align)), 
                          grep("CTAHR", colnames(hm.align)),
                          grep("SCFS", colnames(hm.align))
                          )]

heatmap.2((hm2.in),
          key = T,
          dendrogram = "none",
          trace = "none",
          cexCol = 1.75,
          col = terrain.colors(256), 
          Colv = F, Rowv = F, 
          srtCol = 30,
          margins = c(7, 6),
          main = "Degree of Misalignment"
          )

```


```{r results_wordclouds, cache=TRUE, fig.dim = c(6, 6), echo = FALSE, message=FALSE, warning=FALSE}

## wc.labs <- unlist(lapply(strsplit(names(wc.scfs.program), ": "), function(x) x[[2]]))
wc.labs <- names(wc.scfs.program)

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "SCFS Program", cex = 2)
wordcloud(unlist(kw.scfs.program), 
          rep(1, length(unlist(kw.scfs.program))),
          min.freq = 1, random.order = F,
          rot.per = 0,
          scale = c(2.25, 0.01)
          )
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "SCFS Courses", cex = 2)
wordcloud(unlist(kw.scfs.courses), 
          rep(1, length(unlist(kw.scfs.courses))),
          min.freq = 1, random.order = F,
          rot.per = 0,
          scale = c(2.25, 0.01)
          )
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "CTAHR Program", cex = 2)
wordcloud(unlist(kw.ctahr.program), 
          rep(1, length(unlist(kw.ctahr.program))),
          min.freq = 1, random.order = F,
          rot.per = 0,
          scale = c(2.25, 0.01)
          )
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "CTAHR Courses", cex = 2)
wordcloud(unlist(kw.ctahr.courses), 
          rep(1, length(unlist(kw.ctahr.courses))),
          min.freq = 1, random.order = F,
          rot.per = 0,
          scale = c(2.25, 0.01)
          )
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "USP Program", cex = 2)
wordcloud(unlist(kw.usp.program), 
          rep(1, length(unlist(kw.usp.program))),
          min.freq = 1, random.order = F,
          rot.per = 0,
          scale = c(2.25, 0.01)
          )
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "USP Courses", cex = 2)
wordcloud(unlist(kw.usp.courses), 
          rep(1, length(unlist(kw.usp.courses))),
          min.freq = 1, random.order = F,
          rot.per = 0,
          scale = c(2.25, 0.01)
          )
box(lty = "solid", col = "black")

```


```{r results_wordclouds_lo, cache=TRUE, fig.dim = c(6, 6), echo = FALSE, message=FALSE, warning=FALSE}

## wc.labs <- unlist(lapply(strsplit(names(wc.scfs.program), ": "), function(x) x[[2]]))
wc.labs <- names(wc.scfs.program)

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "SCFS Program", cex = 2)
wordcloud(wc.labs, wc.scfs.program, min.freq = 1, random.order = F, 
          scale = c(2, 0.1), rot.per = 0)
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "SCFS Courses", cex = 2)
wordcloud(wc.labs, wc.scfs.courses, min.freq = 1, random.order = F, 
          scale = c(2, 0.1), rot.per = 0)
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "CTAHR Program", cex = 2)
wordcloud(wc.labs, wc.ctahr.program, min.freq = 1, random.order = F, 
          scale = c(2, 0.1), rot.per = 0)
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "CTAHR Courses", cex = 2)
wordcloud(wc.labs, wc.ctahr.courses, min.freq = 1, random.order = F, 
          scale = c(1, 0.01), rot.per = 0)
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "USP Program", cex = 2)
wordcloud(wc.labs, wc.usp.program, min.freq = 1, random.order = F, 
          scale = c(2, 0.1), rot.per = 0)
box(lty = "solid", col = "black")

layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "USP Courses", cex = 2)
wordcloud(wc.labs, wc.usp.courses, min.freq = 1, random.order = F, 
          scale = c(2, 0.1), rot.per = 0)
box(lty = "solid", col = "black")

```


```{r results_similarity, cache=TRUE, fig.dim = c(7, 7), echo = FALSE}

fviz_pca(kwa.pc, col.var = NA, xlim = c(-5, 5))
fviz_pca(kwa.kw.pc, col.var = NA, xlim = c(-10, 20), ylim = c(-15, 10))

fviz_eig(kwa.pc, addlabels = TRUE)
fviz_eig(kwa.kw.pc, addlabels = TRUE)

```


